#ifndef GESTIONCOMBAT_H_INCLUDED
#define GESTIONCOMBAT_H_INCLUDED

#define NB_FRAME_COUP 2
#define VITESSE_FRAME_COUP 200
#define DEGAT_EPEE 4
#define DEGAT_POING 1
#define DEGAT_HACHE 2
#define DEGAT_PELLE 2
#define DEGAT_PIOCHE 2

#endif // GESTIONCOMBAT_H_INCLUDED
